
--TABLAS
CREATE TABLE Cliente (
documento VARCHAR(50) NOT NULL,
tipoDocumento VARCHAR(50) NOT NULL,
nombre VARCHAR(100) NOT NULL,
correo VARCHAR(50) NOT NULL,
telefono VARCHAR(70) NOT NULL
);

CREATE TABLE Paseador(
documento VARCHAR(50) NOT NULL,
tipoDocumento VARCHAR(50) NOT NULL,
nombre VARCHAR(100) NOT NULL,
correo VARCHAR(50) NOT NULL,
telefono VARCHAR(70) NOT NULL
);

CREATE TABLE Mascota(
id INTEGER NOT NULL,
nombre VARCHAR(50) NOT NULL,
raza VARCHAR(50) NOT NULL,
edad INTEGER NOT NULL,
genero VARCHAR(50) NOT NULL
);

CREATE TABLE Paseo(
id INTEGER NOT NULL,
ruta VARCHAR(200) NOT NULL,
duracion INTEGER NOT NULL
);

CREATE TABLE Subasta(
id INTEGER NOT NULL,
oferta INTEGER NOT NULL
);



--PRIMARIAS

--SECUENCIAS
CREATE SEQUENCE id_mascota;
CREATE SEQUENCE id_paseo;
CREATE SEQUENCE id_subasta;